DO $$BEGIN
  CREATE ROLE pic_store WITH
    -- You should change this default password for real usage.
    LOGIN PASSWORD '6383368ef20d2fa4fac2c0e0d3f53517f024ec9e';
  EXCEPTION WHEN duplicate_object THEN NULL;
END; $$;

ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE CREATE ON SCHEMAS FROM PUBLIC;
DO
$$
BEGIN
  EXECUTE FORMAT('GRANT CONNECT ON DATABASE %s TO pic_store', current_database());
END;
$$;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO pic_store;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO pic_store;
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO pic_store;

